language: java
sudo: false
install: true

jdk:
- oraclejdk8

addons:
  sonarqube:
    organization: code-not-found-spring-kafka
    token:
      secure: $SONAR_TOKEN

env:
- PROJECT_DIR=spring-kafka-avro
- PROJECT_DIR=spring-kafka-avro-bijection
- PROJECT_DIR=spring-kafka-batch-listener
- PROJECT_DIR=spring-kafka-boot
- PROJECT_DIR=spring-kafka-embedded-test
- PROJECT_DIR=spring-kafka-helloworld
- PROJECT_DIR=spring-kafka-integration-helloworld
- PROJECT_DIR=spring-kafka-json


script:
- cd $PROJECT_DIR
- mvn test -B
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

cache:
  directories:
  - $HOME/.m2/repository
  - $HOME/.sonar/cache

notifications:
  email: false
